### PR TITLE
Fix missing dependencies building with make

### PR DESCRIPTION
**Pull request by atosatto**
Fixing issue #6 and switching to `gvt`!

### CODE REVIEW

**Comment by fntlnz** [comment]
@atosatto Thanks!

**Comment by fntlnz** [comment]
@atosatto anyway this doesn't seem to have fixed the _submodule_ problem:

If you look at 

https://github.com/fntlnz/doenter/tree/master/vendor/github.com/goburrow

`serial`  is considered as a submodule. 

while `go-homedir` is not

https://github.com/fntlnz/doenter/tree/master/vendor/github.com/mitchellh

**Comment by atosatto** [comment]
That's why I've implemented this workaround:
https://github.com/fntlnz/doenter/blob/master/Makefile#L19-L21
:stuck_out_tongue_closed_eyes:

I don't know how to fix this. It seems to me something related to Github...
Is it possible?!

**Comment by fntlnz** [comment]
Yes I think that is related to the fact that gvt removes *_test.go files from the source repository so the mitchellh's go-homedir, which have tests is ok while goburrow's serial is not because github recognises it as the same repository and treat it as a submodule.

**Pull request merged**
